### ISSUE TITLE
Add `thelounge` as a project topic

### ISSUE THREAD

**Issue by astorije** [omnivector-solutions/layer-thelounge#2]
Hey there!

On this repo's homepage, you have the possibility to add topics. Could you add `thelounge` as a topic so this repo appears in https://github.com/topics/thelounge?

I am going to suggest GitHub to make it the official topic, now that we have a logo, and a few other repos at this URL.

Thanks!

**Comment by astorije** [comment]
You might want to do that on this repo as well: https://github.com/omnivector-solutions/snap-thelounge

**Comment by jamesbeedy** [comment]
Done and done. @astorije thanks for pointing that out.

**Comment by astorije** [comment]
Awesome, thanks!
